server:
  port: 8085
spring:
  application:
    name: ticket
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host=: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3
eureka:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

datasource:
  springcloudtest:
    url: jdbc:mysql://localhost:3306/spring_cloud_test_microservice
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect